site_name: CORFERIDA (DAGGERHEART), REFERÈNCIA DEL SISTEMA
site_url: https://litusb.github.io/corferida-drs/
repo_url: https://github.com/litusb/corferida-drs
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  favicon: favicon.png
  logo: favicon.png
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      toc_depth: 3
